services:
  php-fpm:
    container_name: php-fpm
    build: .
    networks:
      - speaker_api
    depends_on: 
      - caddy
    env_file:
      - .env

#  php:
#    container_name: php-fpm
#    image: php:8.4-fpm
#    networks:
#      - speaker_api
#    volumes:
#     - .:/var/www/html

  caddy:
    container_name: caddy
    image: caddy:2.10.0
    ports:
      - 8080:8080
    networks:
      - speaker_api
    volumes:
      - .:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  speaker_api:
    driver: bridge
