services:
  php-fpm:
    container_name: php-fpm
    build: 
      context: .
      dockerfile: ./service_php_fpm/Dockerfile
    networks:
      - speaker_api
    depends_on: 
      - caddy
    env_file:
      - .env

  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: ./service_caddy/Dockerfile
    ports:
      - 8080:8080
    networks:
      - speaker_api

networks:
  speaker_api:
    driver: bridge
