services:
  web:
    container_name: web
    build: .
    ports: 
      - 8080:8080
    networks:
      - speaker_api
    depends_on: 
      - php

  php:
    container_name: php-fpm
    image: php:8.4-fpm
    networks:
      - speaker_api

networks:
  speaker_api:
    driver: bridge
